"""empty message

Revision ID: 944c1e0e4878
Revises: d30b24476f96
Create Date: 2026-07-30 11:53:43.021154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944c1e0e4878'
down_revision = 'd30b24476f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
